name: Build and Test
on: [ push, pull_request ]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check.
        run: .github/check-format.sh

  build-and-test:
    name: Build with CMake and run CTest
    runs-on: ubuntu-22.04
    env:
      CC: "clang-14"
    steps:
      - uses: actions/checkout@v3
      - name: Checkout test data
        uses: actions/checkout@v3
        with:
          repository: jepebe/ProcessorTestsBinaries
          path: './tests/processor_tests'
      - name: Create build directory
        run: mkdir build
      - name: Configure CMake project
        run: cmake -B build -H. -DCMAKE_BUILD_TYPE=Release
      - name: Compile project
        run: cmake --build build/ --target all -j4
      - name: Run Tests
        run: ctest --test-dir build -j4
